# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Floating Point Parsing Example
#'
#' This example is adapted from the example of the upstream README.md file, and generalized
#' to be called from R with variable input.
#'
#' @param input A character variable with text to parse including a simple default
#' @param verbose A boolean variable to show or suppress progress, defaults to true
#' @return A floating point scalar is returned on success; in case of parsing failure
#' the function exists via \code{stop()}.
#' @examples
#' parseExample()
parseExample <- function(input = "3.1416 xyz ", verbose = TRUE) {
    .Call(`_RcppFastFloat_parseExample`, input, verbose)
}

